name: "Module-VM-Test"
run-name: Virtual Machine Test Deployment ${{ github.run_id }}
on:
  workflow_dispatch:
    inputs:
      location:
        description: "The location to deploy the test example to."
        required: true
        default: 'uksouth'
        type: choice
        options:
          - 'uksouth'
          - 'ukwest'
  pull_request:
    branches:
      - main

env:
  DEPLOYMENT_FILE: ${{ github.workspace }}/example/example.bicep
  DEPLOYMENT_PARAMETERS: ${{ github.workspace }}/example/development.bicepparam
  DEPLOYMENT_NAME: Module-VirtualMachine
  RESOURCE_GROUP_NAME: virtualMachine-${{ github.event.number }}
  DEPLOYMENT_LOCATION: ${{ github.event.inputs.location || 'uksouth' }}
    
jobs:
  Setup:
    runs-on: ubuntu-latest
    outputs:
      deployment_file: ${{ env.DEPLOYMENT_FILE }}
      deployment_parameters: ${{ env.DEPLOYMENT_PARAMETERS }}
      deployment_name: ${{ env.DEPLOYMENT_NAME }}
      resource_group_name: ${{ env.RESOURCE_GROUP_NAME }}
      deployment_location: ${{ env.DEPLOYMENT_LOCATION }}
    steps:
      - name: Authenticate
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          auth-type: SERVICE_PRINCIPAL
      - name: Create Resource Group
        uses: azure/cli@v2
        with:
          inlineScript: |
            resource_group_exists=$(az group exists --name "${{ inputs.resource_group_name }}")
            echo "Resource Group Name is ${{ inputs.resource_group_name }}"
            if [[ $resource_group_exists == "true" ]]; then
              echo "Resource Group ${{ inputs.resource_group_name }} already exists, continuing"
            else
              echo "Creating Resource Group"
              az group create --name ${{ env.RESOURCE_GROUP_NAME }} --location ${{ env.DEPLOYMENT_LOCATION }} --tags pr_id=${{ github.event.number }} pr=true
            fi
      - run: echo "Completed Setup"

  Validate:
    needs: [Setup]
    uses: scankin/bicep-workflows/.github/workflows/bicep-predeploy.yml@2.0.0
    with: 
      location: ${{ needs.setup.outputs.deployment_location }}
      deployment_file: ${{ needs.setup.outputs.deployment_file }}
      deployment_parameters: ${{ needs.setup.outputs.deployment_parameters }}
      resource_group_name: ${{ needs.setup.outputs.resource_group_name }}
      deployment_name: ${{ needs.setup.outputs.deployment_name }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      
  Deploy:
    needs: [Setup, Validate]
    uses: scankin/bicep-workflows/.github/workflows/bicep-deploy.yml@2.0.0
    with:
      location: ${{ needs.setup.outputs.deployment_location }}
      deployment_file: ${{ needs.setup.outputs.deployment_file }}
      deployment_parameters: ${{ needs.setup.outputs.deployment_parameters }}
      resource_group_name: ${{ needs.setup.outputs.resource_group_name }}
      deployment_name: ${{ needs.setup.outputs.deployment_name }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}